version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - jururuk_network
    volumes:
      - /home/darma4545/nginx.conf:/etc/nginx/nginx.conf
      - jururuk_static:/data/static/
      - jururuk_media:/data/media/
      - jururuk_log:/var/log/nginx/

  goaccess:
    image: allinurl/goaccess:1.5.1
    volumes:
      - jururuk_log:/var/log/nginx/
    ports:
      - 7890:7890
    command: /var/log/nginx/jururuk_access.log -o /var/log/nginx/report.html --log-format COMBINED --real-time-html

  django:
    image: jururuk:5
    networks:
      - jururuk_network
    volumes:
      - jururuk_static:/home/Class_Web/staticfiles/
      - jururuk_media:/home/Class_Web/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD
  mariadb:
    image: mariadb:10.5
    networks:
      - jururuk_network
    volumes:
      - jururuk_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD

    environment:
      MARIADB_DATABASE: jururuk_django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  jururuk_network:

volumes:
  jururuk_static:
  jururuk_media:
  jururuk_mariadb:
  jururuk_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true