version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - jururuk_network
    volumes:
      - /home/darma4545/nginx.conf:/etc/nginx/nginx.conf
      - jururuk_static:/data/static/
      - jururuk_media:/data/media/

  django:
    image: jururuk:5
    networks:
      - jururuk_network
    volumes:
      - jururuk_static:/home/Class_Web/staticfiles/
      - jururuk_media:/home/Class_Web/media/
    secrets:
      - DJANGO_SECRET_KEY

  mariadb:
    image: mariadb:10.5
    networks:
      - jururuk_network
    volumes:
      - jururuk_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD

    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: jururuk_django
      MARIADB_USER: jururuk_django
      MARIADB_PASSWORD: mypassword1234

networks:
  jururuk_network:

volumes:
  jururuk_static:
  jururuk_media:
  jururuk_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_USER_PASSWORD:
    external: true